"""add updated_at to users

Revision ID: 0165521b3d51
Revises: d88dfaf74937
Create Date: 2026-01-26 18:14:43.833417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0165521b3d51'
down_revision: Union[str, Sequence[str], None] = 'd88dfaf74937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'MAINTENANCE', 'CLOSED', name='amenitystatus'), nullable=True),
    sa.Column('open_hours', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenities_id'), 'amenities', ['id'], unique=False)
    op.create_index(op.f('ix_amenities_name'), 'amenities', ['name'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'REJECTED', name='bookingstatus'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('marketplace_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'PENDING', 'SOLD', name='marketplaceitemstatus'), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_items_category'), 'marketplace_items', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_items_id'), 'marketplace_items', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'ALERT', 'SUCCESS', name='notificationtype'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('staff_type', sa.Enum('MAID', 'DRIVER', 'COOK', 'GARDENER', 'NANNY', 'OTHER', name='stafftype'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLISTED', name='staffstatus'), nullable=True),
    sa.Column('id_proof_number', sa.String(), nullable=True),
    sa.Column('id_proof_url', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('access_code', sa.String(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_access_code'), 'staff', ['access_code'], unique=True)
    op.create_index(op.f('ix_staff_full_name'), 'staff', ['full_name'], unique=False)
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_index(op.f('ix_staff_phone_number'), 'staff', ['phone_number'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('PLUMBING', 'ELECTRICAL', 'SECURITY', 'LANDSCAPING', 'OTHER', name='ticketcategory'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_table('staff_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', name='attendancestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_attendance_id'), 'staff_attendance', ['id'], unique=False)
    op.add_column('bills', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('fee_definitions_name_key'), 'fee_definitions', type_='unique')
    op.create_index(op.f('ix_fee_definitions_name'), 'fee_definitions', ['name'], unique=False)
    op.alter_column('incidents', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notices', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('address', sa.String(), nullable=False))
    op.drop_index(op.f('ix_properties_unit_number'), table_name='properties')
    op.create_index(op.f('ix_properties_address'), 'properties', ['address'], unique=True)
    op.drop_column('properties', 'unit_number')
    op.drop_column('properties', 'block_number')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.add_column('visitors', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitors', 'updated_at')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'updated_at')
    op.add_column('properties', sa.Column('block_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('unit_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_properties_address'), table_name='properties')
    op.create_index(op.f('ix_properties_unit_number'), 'properties', ['unit_number'], unique=True)
    op.drop_column('properties', 'address')
    op.drop_column('payments', 'updated_at')
    op.alter_column('notices', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('incidents', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_fee_definitions_name'), table_name='fee_definitions')
    op.create_unique_constraint(op.f('fee_definitions_name_key'), 'fee_definitions', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('bills', 'updated_at')
    op.drop_index(op.f('ix_staff_attendance_id'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_staff_phone_number'), table_name='staff')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_full_name'), table_name='staff')
    op.drop_index(op.f('ix_staff_access_code'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_marketplace_items_id'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_category'), table_name='marketplace_items')
    op.drop_table('marketplace_items')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_amenities_name'), table_name='amenities')
    op.drop_index(op.f('ix_amenities_id'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
