"""add tenant_id to remaining models

Revision ID: 07391ffa4c06
Revises: b2b014a51c32
Create Date: 2026-01-27 10:21:53.420605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07391ffa4c06'
down_revision: Union[str, Sequence[str], None] = 'b2b014a51c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'tenants', ['tenant_id'], ['id'])
    # op.add_column('parcels', sa.Column('tenant_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'parcels', 'tenants', ['tenant_id'], ['id'])
    op.add_column('vehicles', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'tenant_id')
    # op.drop_constraint(None, 'parcels', type_='foreignkey')
    # op.drop_column('parcels', 'tenant_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'tenant_id')
    # ### end Alembic commands ###
