"""Add items carried in and out columns to visitors

Revision ID: 200c08e19c82
Revises: d715c15ef9a6
Create Date: 2026-01-26 09:20:39.999959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '200c08e19c82'
down_revision: Union[str, Sequence[str], None] = 'd715c15ef9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('incidents', 'updated_at')
    op.add_column('visitors', sa.Column('items_carried_in', sa.String(), nullable=True))
    op.add_column('visitors', sa.Column('items_carried_out', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitors', 'items_carried_out')
    op.drop_column('visitors', 'items_carried_in')
    op.add_column('incidents', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('incidents', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
