"""add_tenant_id_to_remaining_models

Revision ID: 2d3299c883ee
Revises: 07391ffa4c06
Create Date: 2026-01-27 10:24:32.993917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3299c883ee'
down_revision: Union[str, Sequence[str], None] = '07391ffa4c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bills', 'tenants', ['tenant_id'], ['id'])
    op.add_column('visitors', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'visitors', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_column('visitors', 'tenant_id')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'tenant_id')
    # ### end Alembic commands ###
