"""add is_password_changed to users

Revision ID: 3e614d97c959
Revises: 200c08e19c82
Create Date: 2026-01-26 09:37:20.232157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e614d97c959'
down_revision: Union[str, Sequence[str], None] = '200c08e19c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_password_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_password_changed')
    # ### end Alembic commands ###
