"""add image_url to vehicles

Revision ID: 54db8b0a0952
Revises: b65a58f157fc
Create Date: 2026-01-26 21:19:35.558645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54db8b0a0952'
down_revision: Union[str, Sequence[str], None] = 'b65a58f157fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'image_url')
    # ### end Alembic commands ###
