"""Add tenant_id to community models

Revision ID: 5b7f32fc0c52
Revises: 1a2b3c4d5e6f
Create Date: 2026-01-27 09:14:50.835268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7f32fc0c52'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenities', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'amenities', 'tenants', ['tenant_id'], ['id'])
    op.add_column('blacklist', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blacklist', 'tenants', ['tenant_id'], ['id'])
    op.add_column('fee_definitions', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fee_definitions', 'tenants', ['tenant_id'], ['id'])
    op.add_column('properties', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'tenants', ['tenant_id'], ['id'])
    op.add_column('staff', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staff', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('uq_tenants_slug'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_unique_constraint(op.f('uq_tenants_slug'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'tenant_id')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'tenant_id')
    op.drop_constraint(None, 'fee_definitions', type_='foreignkey')
    op.drop_column('fee_definitions', 'tenant_id')
    op.drop_constraint(None, 'blacklist', type_='foreignkey')
    op.drop_column('blacklist', 'tenant_id')
    op.drop_constraint(None, 'amenities', type_='foreignkey')
    op.drop_column('amenities', 'tenant_id')
    # ### end Alembic commands ###
