"""Add profile_picture and vehicle image_url

Revision ID: 6012406cd5e2
Revises: cfa32fe03b53
Create Date: 2026-01-26 21:41:47.963441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6012406cd5e2'
down_revision: Union[str, Sequence[str], None] = 'cfa32fe03b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
