"""fix_marketplace_model

Revision ID: 9f3894fbb21d
Revises: 0165521b3d51
Create Date: 2026-01-26 22:55:55.673844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f3894fbb21d'
down_revision: Union[str, Sequence[str], None] = '0165521b3d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketplace_items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('marketplace_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_marketplace_items_category'), table_name='marketplace_items')
    op.drop_column('staff', 'id_proof_url')
    op.drop_column('staff', 'id_proof_number')
    op.drop_column('staff', 'photo_url')
    op.add_column('staff_attendance', sa.Column('check_in', sa.DateTime(timezone=True), nullable=False))
    op.add_column('staff_attendance', sa.Column('check_out', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('staff_attendance', 'check_in_time')
    op.drop_column('staff_attendance', 'check_out_time')
    op.drop_column('staff_attendance', 'created_at')
    op.drop_column('staff_attendance', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_attendance', sa.Column('status', postgresql.ENUM('PRESENT', 'ABSENT', name='attendancestatus'), autoincrement=False, nullable=True))
    op.add_column('staff_attendance', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('staff_attendance', sa.Column('check_out_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('staff_attendance', sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('staff_attendance', 'check_out')
    op.drop_column('staff_attendance', 'check_in')
    op.add_column('staff', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('id_proof_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('id_proof_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_marketplace_items_category'), 'marketplace_items', ['category'], unique=False)
    op.alter_column('marketplace_items', 'price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('marketplace_items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
