"""add_tenant_id_to_more_community_models

Revision ID: b2b014a51c32
Revises: 5b7f32fc0c52
Create Date: 2026-01-27 09:22:45.205212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b014a51c32'
down_revision: Union[str, Sequence[str], None] = '5b7f32fc0c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_documents', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'community_documents', 'tenants', ['tenant_id'], ['id'])
    op.add_column('incidents', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'tenants', ['tenant_id'], ['id'])
    op.add_column('marketplace_items', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marketplace_items', 'tenants', ['tenant_id'], ['id'])
    op.add_column('notices', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notices', 'tenants', ['tenant_id'], ['id'])
    op.add_column('patrol_logs', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patrol_logs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('polls', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'polls', 'tenants', ['tenant_id'], ['id'])
    op.add_column('tickets', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'tenant_id')
    op.drop_constraint(None, 'polls', type_='foreignkey')
    op.drop_column('polls', 'tenant_id')
    op.drop_constraint(None, 'patrol_logs', type_='foreignkey')
    op.drop_column('patrol_logs', 'tenant_id')
    op.drop_constraint(None, 'notices', type_='foreignkey')
    op.drop_column('notices', 'tenant_id')
    op.drop_constraint(None, 'marketplace_items', type_='foreignkey')
    op.drop_column('marketplace_items', 'tenant_id')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'tenant_id')
    op.drop_constraint(None, 'community_documents', type_='foreignkey')
    op.drop_column('community_documents', 'tenant_id')
    # ### end Alembic commands ###
