"""add_tenant_id_to_payment_model

Revision ID: c717c63ff09f
Revises: 2d3299c883ee
Create Date: 2026-01-27 10:26:41.058836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c717c63ff09f'
down_revision: Union[str, Sequence[str], None] = '2d3299c883ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'tenant_id')
    # ### end Alembic commands ###
