"""add_subscription_fields

Revision ID: ce8424712183
Revises: fe16ec335ff2
Create Date: 2026-01-27 14:40:49.351309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8424712183'
down_revision: Union[str, Sequence[str], None] = 'fe16ec335ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'subscription_end_date')
    op.drop_column('tenants', 'plan')
    # ### end Alembic commands ###
