"""add tenant package limits

Revision ID: fe16ec335ff2
Revises: 7c9fb21d6cf6
Create Date: 2026-01-27 14:20:01.808239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe16ec335ff2'
down_revision: Union[str, Sequence[str], None] = '7c9fb21d6cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('max_admins', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_guards', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_residents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'max_residents')
    op.drop_column('tenants', 'max_guards')
    op.drop_column('tenants', 'max_admins')
    # ### end Alembic commands ###
