"""add house address and incident priority

Revision ID: ff94bc67131b
Revises: 3e614d97c959
Create Date: 2026-01-26 11:55:39.061841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff94bc67131b'
down_revision: Union[str, Sequence[str], None] = '3e614d97c959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enum type
    incident_priority = sa.Enum('low', 'medium', 'high', 'critical', name='incidentpriority')
    incident_priority.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('house_address', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('priority', incident_priority, server_default='medium', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'priority')
    op.drop_column('users', 'house_address')
    
    # Drop Enum
    sa.Enum(name='incidentpriority').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
